AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable

Gemspec/RequiredRubyVersion:
  Enabled: false

Layout/LineLength:
  Max: 130

Metrics/AbcSize:
  Max: 50
Metrics/BlockLength:
  Max: 50
  Exclude:
    - 'spec/**/*.rb'
Metrics/MethodLength:
  Max: 200
Metrics/ModuleLength:
  Max: 200
Metrics/ParameterLists:
  Enabled: false

Naming/VariableNumber:
  Enabled: false

Style/Documentation:
  Enabled: false
Style/HashSyntax:
  Enabled: false
Style/OptionalBooleanParameter:
  Enabled: false
Style/StringLiterals:
  Enabled: false
